config/routes.rb
Rails.application.routes.draw do


# 管理者routingd

devise_for :admins, :controllers => {
 :sessions => 'admins/sessions'
}

 namespace :admin do
  	resources :items
  	resources :genres, only: [:index, :create, :edit, :update]
  	get 'end_users' => 'end_users#index'
    resources :orders, only: [:index, :show, :update]
    resources :order_detiles, only: [:update]
  end


# ユーザーrouting


  devise_for :end_users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}

namespace :public do
   resource :end_users, only: [:edit, :update, :show]
    delete '/end_users' => 'end_users#hide'
    resources :items, only: [:index, :show]
    get 'end_users/comfilm' => 'end_users#comfilm'
    resources :cart_items
    delete '/cart_items' => 'cart_items#destroy_all', as: :destroy_all
    get 'orders/complete' => 'orders#complete'
    get 'orders/verification' => 'orders#verification'
    resources :orders, only: [:index, :show, :new, :create]
    resources :addresses
  end

  scope module: :public do
  	root 'items#index'
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

	belongs_to :end_user
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :end_user
belongs_to :item
end

app/models/end_user.rb
class EndUser < ApplicationRecord
 acts_as_paranoid
 # validates_as_paranoid
 # validates_uniqueness_of_without_deleted :family_name, :first_name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :kana_family_name, presence: true
  validates :kana_first_name, presence: true
  validates :email, presence: true
  validates :post_number, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true

  has_many :cart_items
  has_many :orders
  has_many :addresses
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	belongs_to :genre
	has_many :cart_items
	has_many :order_detiles
def posted_by?(end_user)
	cart_items.where(end_user_id: end_user.id).exists?
end
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :end_user
	has_many :order_detiles
	enum order_status: { waiting: 0, confilm: 1, doing: 2, prefre: 3, complete: 4 }
end

app/models/order_detile.rb
class OrderDetile < ApplicationRecord
	belongs_to :order
	belongs_to :item
	enum production_status: { notyet: 0, waiting: 1, doing: 2, complete: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

	def index
		@genres = Genre.all
		@genre = Genre.new
	end

	def create
		genre = Genre.new(genre_params)
		genre.save
		redirect_to admin_genres_path
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		genre = Genre.find(params[:id])
		genre.update(genre_params)
		redirect_to admin_genres_path
	end

	private
	def genre_params
		params.require(:genre).permit(:name, :active_status)
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
	def index
		@items = Item.all
		if params[:search] != nil
			@items = Item.where("name LIKE?", '%' + params[:search] + '%')
		else
			@items = Item.all
		end
	end

	def new
		@item = Item.new
	end

	def create
		item = Item.new(item_params)
		item.save
		redirect_to admin_item_path(item.id)
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
	end

	def update
	end

	private
	def item_params
		params.require(:item).permit(:name, :introduction, :image, :genre_id, :untax_price, :sale_status)
	end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	def index
		@orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
	end

	def update
		order = Order.find(params[:id])
		order.update(order_params)
		if order.order_status_before_type_cast == 1
			order_detiles = order.order_detiles
			order_detiles.each do |order_detile|
				order_detile.production_status = 1
				order_detile.update(order_detile_params)
			end
		end
		redirect_to admin_order_path(order.id)
	end

	private
	def order_params
		params.require(:order).permit(:order_status)
	end

	def order_detile_params
		params.permit(:production_status)
	end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/book_helper.rb
module Admin::BookHelper
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_detiles_helper.rb
module Admin::OrderDetilesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/admin/genres/edit.html.erb
<%= form_for @genre,url: admin_genre_path do  |f| %>
  <%= f.text_field :name %>
  <%= f.radio_button :active_status, true %>
  <%= f.label :active_status, "有効" %>
  <%= f.radio_button :active_status, false %>
  <%= f.label :active_status, "無効" %>
  <%= f.submit "追加" %>
<% end %>

app/views/admin/genres/index.html.erb
<%= form_for @genre,url: admin_genres_path do  |f| %>
  <%= f.text_field :name %>
  <%= f.radio_button :active_status, true %>
  <%= f.label :active_status, "有効" %>
  <%= f.radio_button :active_status, false %>
  <%= f.label :active_status, "無効" %>
  <%= f.submit "追加" %>
<% end %>



<table>
	<thead>
		<tr>
			<th>ジャンル</th>
			<th>状態</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @genres.each do |genre| %>
		<tr>
			<td><%= genre.name %></td>
			<% if genre.active_status == true %>
    　　　　　　<td>有効</td>
 　　　　　   <% else %>
               <td>無効</td>
            <% end %>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id) %><td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/items/index.html.erb
<h1>管理者用商品一覧画面</h1>

<%= form_with(url: admin_items_path, method: :get, local: true) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索する'  %>
<% end %>


<%= link_to "新規商品登録",new_admin_item_path %><br>
<table>
	<thead>
		<tr>
			<th>商品ID</th>
			<th>商品名</th>
			<th>税抜き価格</th>
			<th>ジャンル</th>
			<th>販売ステータス</th>
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= item.id %></td>
			<td><%= item.name %></td>
			<td><%= item.untax_price %></td>
			<td><%= item.genre.name %></td>
			<% if item.sale_status == true %>
			  <td>販売中</td>
			<% else %>
			  <td>販売停止中</td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/items/new.html.erb
<%= form_for @item, url: admin_items_path  do |f| %>

  <%= f.attachment_field :image %><br>
  <%= f.label :商品名 %>
  <%= f.text_field :name %><br>
  <%= f.label :商品説明 %>
  <%= f.text_area :introduction %><br>
  <%= f.label :商品ジャンル %>
  <%= f.collection_select :genre_id, Genre.all, :id, :name%><br>
  <%= f.label :税抜き価格　%>
  <%= f.text_field :untax_price %><br>
  <%= f.radio_button :sale_status, true %>
  <%= f.label :sale_status, "販売中" %>
  <%= f.radio_button :sale_status, false %>
  <%= f.label :sale_status, "販売停止" %>
  <%= f.submit "新規登録" %>
<% end %>

app/views/admin/items/show.html.erb
<br>
<%= attachment_image_tag @item, :image , :fill, 100, 100, fallback: "no_image.png", size: "100x100" %>

<p>商品名</p>
<%= @item.name %><br>
<p>商品紹介</p>
<%= @item.introduction %>
<P>ジャンル</P>
<%= @item.genre.name %>
<br>

<p>税込価格(税抜き価格)</p>
<%= @item.untax_price*108/100 %>(<%= @item.untax_price %>)円<br>
<p>販売ステータス</p>
<% if @item.sale_status == true %>
  <p>販売中</p>
<% else %>
  <p>販売停止</p>
<% end %>

app/views/admin/orders/index.html.erb
<h1>注文履歴一覧</h1>

<table>
	<thead>
		<tr>
			<th>購入日時</th>
			<th>購入者</th>
			<th>注文個数</th>
			<th>注文ステータス</th>
		</tr>
	</thead>
	<tbody>
		<% @orders.each do |order| %>
		<tr>
			<td>
				<%= link_to admin_order_path(order.id) do %>
				<%= order.created_at.to_s(:datetime_jp) %>
				<% end %>
			<td>
			<td><%= order.end_user.family_name %><%= order.end_user.first_name %></td>
			<td>
				<% @item_amount = 0 %>
				<%  order.order_detiles.each do |order_detile| %>
				  <% @item_amount += order_detile.amount %>
				<% end %>
				<%= @item_amount %>
			</td>
			<td><%= order.order_status_i18n %></td>

		</tr>
		<% end %>

	</tbody>
</table>

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>

<table>
	<tbody>
		<tr>
			<td>購入者</td>
			<td><%= @order.end_user.family_name %><%= @order.end_user.first_name %></td>
		</tr>
		<tr>
			<td>配送先</td>
			<td><%= @order.post_number %><%= @order.address %><%= @order.name %> </td>
		</tr>
		<tr>
			<td>支払い方法</td>
			<td>
				<% if @order.payment == 0 %>
				  <p>クレジットカード</p>
				<% elsif @order.payment ==1 %>
				  <P>銀行振込</P>
				<% else %>
				  <P>支払い方法が選択されていません。</P>
				<% end %>
			</td>
		</tr>
		<tr>
			<td>注文ステータス</td>
			<td>
				<%= form_with(model: @order, url:  admin_order_path(@order.id), method: :put, local: true) do |f| %>
					<%= f.select :order_status, Order.order_statuses_i18n.invert, {} %>
					<%= f.submit '更新' %>
				<% end %>
			</td>
		</tr>
	</tbody>
</table>


	<table border>
		</caption>
		<thead>
			<tr>
				<th>商品名</th>
				<th>単価(税込)</th>
				<th>数量</th>
				<th>小計</th>
				<th>製品ステータス</th>
			</tr>
		</thead>
		<tbody>
			<% @order.order_detiles.each do |order_detile| %>
				<tr>
					<td><%= order_detile.item.name %></td>
					<td><%= order_detile.price %></td>
					<td><%= order_detile.amount %></td>
					<td><%= order_detile.price*order_detile.amount %></td>
					<td>
						<%= form_with(model: order_detile, url:  admin_order_detile_path(order_detile.id), method: :put, local: true) do |f| %>
							<%= f.select :production_status, OrderDetile.production_statuses_i18n.invert, {} %>
							<%= f.submit '更新' %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<table>
		<tbody>
			<tr>
				<td>商品合計</td>
				<td><%= @order.total_price %>円</td>
			</tr>
			<tr>
				<td>送料</td>
				<td><%= @order.postage %>円</td>
			</tr>
			<tr>
				<td>請求金額合計</td>
				<td><%= @order.total_price + @order.postage %>円</td>
			</tr>
		</tbody>
	</table>